### ISSUE TITLE
check years of data used by IBMs

### ISSUE THREAD

**Issue by cmlegault** [cmlegault/IBMWG#40]
Desire is to have year t and t+1 catch advice based on catch through year t-2, fall index through year t-2, and spring index through year t-1 (when fall and subsequent spring are averaged). Is this what is happening in wham_mse_function.R line 195:
observed_sim = get.IBM.input(y=observed_sim, i=year, adv.yr = adv.yr)

When look at individual runs, it appears that index and catch are available to IBMs through year t when catch advice provided for years t and t+1 (for example, the final advice for years 89 and 90 are based on catch and indices through years 89). Am I misreading the inputs?

**Comment by JDeroba** [comment]
We should double check that expanded_survey IBM is lagging indices correctly too.

**Comment by rich-bell** [comment]
Adjusted the indexing to provide the correct years of spring survey, fall survey, annual survey and catch to the IBM functions.  As discussed on the call, if the assessment is done mid year in year 50 to provide catch advise for year 51, the available data are: spring survey through year 50, fall survey through year 49, and catch through year 49.  

The annual survey is the mean of the spring survey in year t and the fall survey in year t-1 to provide an estimate of abundance for Jan 1, in year t.  This means that in year one, there is a spring survey, but no fall survey the year prior so the mean is roughly half the true value (spr +0)/2.  The annual survey index has been adjusted to leave out year one.  The annual survey index (y$index) goes from year 2:t.  Indexing the annual survey this way means the survey and catch vectors are the same length.  For IBM functions that needed survey and catch to be the same length, they should be all set.  It does mean that the catch that occurs in year one is now aligned with the estimated survey biomass on Jan 1, year two.

The seasonal survey index goes from year 1 to year t so year one is included.  The fall survey in the terminal year is now an NA however as this value is not available to the assessment.  I made it an NA instead of a zero so that functions would produce an error if it is not accounted for.  The same is true for the numbers at age.  Years 1:t are available, but the terminal year in the fall is a row of NA's.  I have not run it through all the functions yet, but hopefully they do not all blow up.  I will take a look at expand biomass soon

**Comment by timjmiller** [comment]
@rich-bell This now gives this error in the mse test:

Error in rbind(caa_survey_two_base, caa_survey_two_proj)[1:base_yr + i - : only 0's may be mixed with negative subscripts

It appears that offset_fall_I (=2) is causing negative rows to be accessed from this matrix because 1:base_yr + i - offset_fall_I will start at negative numbers for i<=1

**Comment by rich-bell** [comment]
@timjmiller   Looks like I forgot to add the parentheses 1:(base_yr + i - offset_fall_I) on line 268 so the vector was starting at zero instead of one.  I believe that issue is corrected now. sorry

**Comment by cmlegault** [comment]
All IBMs appear to be working correctly. Thanks everyone!
