### ISSUE TITLE
check index of adv.yr

### ISSUE THREAD

**Issue by JDeroba** [cmlegault/IBMWG#9]
in the wham_mse_functions.R script just check to see that JJD did the indexing with adv.yr correctly.  I think I got it, but another set of eyes appreciated.

**Comment by gavinfay** [comment]
Think this seems to be right (F's are being updated in blocks of `adv.yr` duration).
Made some changes to loop over assessment (advice update) years to simplify bookkeeping (at least for me) & keep the sims.results objects indexing with the numbers of the assessments/advice updates, rather than skipping indexing. In practice I don't think this matters because we are just returning the final object at the end of the projection period.
